version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: test-postgres-14.2
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env.test
  test:
    build: .
    depends_on:
      - db
volumes:
  test_postgres_data: {}
